"""Convert the FireNet Pascal-VOC set (data/firenet/) into a YOLO detection dataset.

Input  : data/firenet/{train,validation}/{images,annotations}/*.{jpg,xml}
Output : data/firenet_yolo/{images,labels}/{train,val}/  +  data/firenet_yolo/firenet.yaml

Single class: 0 = fire.  Deterministic; safe to re-run.
"""
from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

from backend.core.config import REPO_ROOT

SRC = REPO_ROOT / "data" / "firenet"
DST = REPO_ROOT / "data" / "firenet_yolo"
CLASSES = ["fire"]


def _convert_split(split_src: str, split_dst: str) -> int:
    img_dir = SRC / split_src / "images"
    ann_dir = SRC / split_src / "annotations"
    out_img = DST / "images" / split_dst
    out_lbl = DST / "labels" / split_dst
    out_img.mkdir(parents=True, exist_ok=True)
    out_lbl.mkdir(parents=True, exist_ok=True)

    n = 0
    for img in sorted(img_dir.glob("*.jpg")):
        xml = ann_dir / f"{img.stem}.xml"
        if not xml.exists():
            continue
        root = ET.parse(xml).getroot()
        w = float(root.findtext("size/width") or 0)
        h = float(root.findtext("size/height") or 0)
        if not (w and h):
            from PIL import Image

            with Image.open(img) as im:
                w, h = im.size
        lines = []
        for obj in root.findall("object"):
            name = (obj.findtext("name") or "").strip().lower()
            cls = 0 if name in ("fire", "flame") else 0  # single-class set
            b = obj.find("bndbox")
            x1, y1 = float(b.findtext("xmin")), float(b.findtext("ymin"))
            x2, y2 = float(b.findtext("xmax")), float(b.findtext("ymax"))
            cx, cy = (x1 + x2) / 2 / w, (y1 + y2) / 2 / h
            bw, bh = (x2 - x1) / w, (y2 - y1) / h
            if bw <= 0 or bh <= 0:
                continue
            lines.append(f"{cls} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")
        (out_lbl / f"{img.stem}.txt").write_text("\n".join(lines), encoding="utf-8")
        # copy image (hardlink where possible to save space)
        target = out_img / img.name
        if not target.exists():
            try:
                target.hardlink_to(img)
            except OSError:
                target.write_bytes(img.read_bytes())
        n += 1
    return n


def main() -> Path:
    if not SRC.exists():
        raise FileNotFoundError(f"{SRC} not found — download FireNet first (see data/README.md)")
    ntr = _convert_split("train", "train")
    nva = _convert_split("validation", "val")

    yaml = DST / "firenet.yaml"
    yaml.write_text(
        "# FireNet -> YOLO detection dataset (auto-generated by prepare_firenet.py)\n"
        f"path: {DST.as_posix()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "names:\n  0: fire\n",
        encoding="utf-8",
    )
    print(f"FireNet -> YOLO: train={ntr}  val={nva}  yaml={yaml}")
    return yaml


if __name__ == "__main__":
    main()
