"""initial schema: drones, telemetry, incidents, response_plans, alerts

Revision ID: bb0db45cc726
Revises: 
Create Date: 2026-09-09 23:37:10.227931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0db45cc726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_sign', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drones_call_sign'), ['call_sign'], unique=True)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('detected_class', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('snapshot_key', sa.String(length=256), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=False),
    sa.Column('wind_dir_deg', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('fuel_dryness', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_drone_id'), ['drone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_ts'), ['ts'], unique=False)

    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('bearing_deg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_drone_id'), ['drone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_ts'), ['ts'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_class', sa.String(length=16), nullable=False),
    sa.Column('recipient_role', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_ts'), ['ts'], unique=False)

    op.create_table('response_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_markdown', sa.Text(), nullable=False),
    sa.Column('llm_mode', sa.String(length=16), nullable=False),
    sa.Column('retrieved_sources', sa.Text(), nullable=False),
    sa.Column('insufficient_context', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_plans_incident_id'), ['incident_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_plans_incident_id'))

    op.drop_table('response_plans')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_ts'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_ts'))
        batch_op.drop_index(batch_op.f('ix_telemetry_drone_id'))

    op.drop_table('telemetry')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_ts'))
        batch_op.drop_index(batch_op.f('ix_incidents_drone_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drones_call_sign'))

    op.drop_table('drones')
    # ### end Alembic commands ###
